### ISSUE TITLE
[BUG] Browser Action Issue

### ISSUE THREAD

**Issue by PerilousTheGreat** [openbullet/openbullet#336]
I'm trying to use the Browser Action block, however, when I use the block for either chrome/firefox I am receiving this error.

`System.InvalidOperationException: session not created: Chrome version must be between 71 and 75
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 6.1.7601 SP1 x86_64) (SessionNotCreated)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary 2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options)
   at RuriLib.SBlockBrowserAction.OpenBrowser(BotData data)`

I am receiving this problem with both Openbullet 1.0.0 and 1.1.3
How do I fix this?

**Version**
 - Version [e.g. 1.1.3]

**Comment by openbullet** [comment]
Hi. All you need to do is update chromedriver.exe, as soon as I have time I will update it and push a fix.

**Comment by winuser** [comment]
I replaced the chromedriver with latest version, but also still same error

**Comment by openbullet** [comment]
Done

**Comment by PerilousTheGreat** [comment]
Hi, its still crashing
