### ISSUE TITLE
[BUG] Error on opening browser selenium

### ISSUE THREAD

**Issue by Rayyos** [openbullet/openbullet#672]
Opening browser...
OpenQA.Selenium.DriverServiceNotFoundException: The chromedriver.exe file does not exist in the current directory or in a directory on the PATH environment variable. The driver can be downloaded at http://chromedriver.storage.googleapis.com/index.html.
   at OpenQA.Selenium.DriverService.FindDriverServiceExecutable(String executableName, Uri downloadUrl)
   at OpenQA.Selenium.Chrome.ChromeDriverService.CreateDefaultService()
   at RuriLib.SBlockBrowserAction.OpenBrowser(BotData data)
Executed browser action Open on input 
===== DEBUGGER ENDED AFTER 0.096 SECOND(S) WITH STATUS: NONE =====

**Comment by openbullet** [comment]
Move chromedriver.exe to the bin folder
