### ISSUE TITLE
[BUG]"Could not find/parse environment settings file. Please fix the issue and try again.

### ISSUE THREAD

**Issue by luam2007** [openbullet/openbullet#850]
Hey, so last night I was using Openbullet and it worked but then my computer crashed, and no each time I try and open it, nothing happens. But when I open it with CMD it says "Could not find/parse environment settings file. Please fix the issue and try again."  Even though my Environment file looks fine.
![image](https://user-images.githubusercontent.com/76477955/167946727-895a7d20-7450-4708-a67d-739bffed2d38.png)

Inside my log file it says:
[FATAL][Application.Current.DispatcherUnhandledException] UHANDLED EXCEPTION
System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'OpenBullet.MainWindow' that matches the specified binding constraints threw an exception. ---> System.InvalidCastException: Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.DataPage'.
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.QueryCursor.Fetch(TransactionService trans, DataService data, BsonReader bsonReader)
   at LiteDB.LiteEngine.<Find>d__9.MoveNext()
   at LiteDB.LiteEngine.<Find>d__13.MoveNext()
   at LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
   at System.Collections.ObjectModel.ObservableCollection`1.CopyFrom(IEnumerable`1 collection)
   at System.Collections.ObjectModel.ObservableCollection`1..ctor(IEnumerable`1 collection)
   at OpenBullet.ViewModels.HitsDBViewModel.RefreshList() in C:\projects\openbullet\OpenBullet\ViewModels\HitsDBViewModel.cs:line 131
   at OpenBullet.Views.Main.HitsDB..ctor() in C:\projects\openbullet\OpenBullet\Views\Main\HitsDB.xaml.cs:line 48
   at OpenBullet.MainWindow..ctor() in C:\projects\openbullet\OpenBullet\MainWindow.xaml.cs:line 235
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)[FATAL][AppDomain.CurrentDomain.UnhandledException] UHANDLED EXCEPTION
System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'OpenBullet.MainWindow' that matches the specified binding constraints threw an exception. ---> System.InvalidCastException: Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.DataPage'.
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.QueryCursor.Fetch(TransactionService trans, DataService data, BsonReader bsonReader)
   at LiteDB.LiteEngine.<Find>d__9.MoveNext()
   at LiteDB.LiteEngine.<Find>d__13.MoveNext()
   at LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
   at System.Collections.ObjectModel.ObservableCollection`1.CopyFrom(IEnumerable`1 collection)
   at System.Collections.ObjectModel.ObservableCollection`1..ctor(IEnumerable`1 collection)
   at OpenBullet.ViewModels.HitsDBViewModel.RefreshList() in C:\projects\openbullet\OpenBullet\ViewModels\HitsDBViewModel.cs:line 131
   at OpenBullet.Views.Main.HitsDB..ctor() in C:\projects\openbullet\OpenBullet\Views\Main\HitsDB.xaml.cs:line 48
   at OpenBullet.MainWindow..ctor() in C:\projects\openbullet\OpenBullet\MainWindow.xaml.cs:line 235
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at OpenBullet.App.Main()

**Comment by openbullet** [comment]
I feel like the DB got corrupted. You should really switch to OB2 since OB1 is out of support, sorry

**Comment by openbullet** [comment]
I feel like the DB got corrupted. You should really switch to OB2 since OB1 is out of support, sorry

**Comment by luam2007** [comment]
Is there anyway to get my hits back which were on the openbullet db or would I have to recheck everything?

**Comment by openbullet** [comment]
I don't think you can easily recover the DB once it's corrupted. Please switch to OB2

**Comment by zzzydrex** [comment]
Hi, i have the same issue with the new SilverBullet 1.1.4 update, "Could not find / parse the Environment Settings file. Please fix the issue and try again.". I tried to add the environment.ini file to the Settings folder but it still dosn't work. Here are my logs :


[FATAL][Application.Current.DispatcherUnhandledException] UHANDLED EXCEPTION
System.Windows.Markup.XamlParseException: Invocation of the constructor on the 'OpenBullet.MainWindow' type that matches the specified binding constraints has thrown an exception. ---> LiteDB.LiteException: The file is not a valid LiteDB database format or contains an invalid password.
   to LiteDB.Engine.HeaderPage.LoadPage()
   to LiteDB.Engine.LiteEngine..ctor(EngineSettings settings)
   to LiteDB.SharedEngine.OpenDatabase()
   LiteDB.SharedEngine.Query(String collection, Query query)
   to LiteDB.LiteQueryable`1.<ToDocuments>d__26.MoveNext()
   to System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   to System.Collections.ObjectModel.ObservableCollection`1.CopyFrom(IEnumerable`1 collection)
   to System.Collections.ObjectModel.ObservableCollection`1..ctor(IEnumerable`1 collection)
   to OpenBullet.ViewModels.WordlistManagerViewModel.RefreshList() in D:\Projects\Desktop\SilverBullet\OpenBullet\ViewModels\WordlistManagerViewModel.cs:line 102
   to OpenBullet.ViewModels.WordlistManagerViewModel..ctor() in D:\Projects\Desktop\SilverBullet\OpenBullet\ViewModels\WordlistManagerViewModel.cs:line 38
   to OpenBullet.MainWindow..ctor() in D:\Projects\Desktop\SilverBullet\OpenBullet\MainWindow.xaml.cs:line 248
   --- End of internal exception stack trace ---
   to System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   to System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   to System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   to System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   to System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   to System.Windows.Application.DoStartup()
   to System.Windows.Application.<.ctor>b__1_0(Object unused)
   to System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   to System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) [FATAL][Dispatcher_UnhandledException] UHANDLED EXCEPTION
System.Windows.Markup.XamlParseException : Invoking the constructor on the 'OpenBullet.MainWindow' type that matches the specified binding constraints has thrown an exception. ---> LiteDB.LiteException: The file is not a valid LiteDB database format or contains an invalid password.
   to LiteDB.Engine.HeaderPage.LoadPage()
   to LiteDB.Engine.LiteEngine..ctor(EngineSettings settings)
   to LiteDB.SharedEngine.OpenDatabase()
   LiteDB.SharedEngine.Query(String collection, Query query)
   to LiteDB.LiteQueryable`1.<ToDocuments>d__26.MoveNext()
   to System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   to System.Collections.ObjectModel.ObservableCollection`1.CopyFrom(IEnumerable`1 collection)
   to System.Collections.ObjectModel.ObservableCollection`1..ctor(IEnumerable`1 collection)
   to OpenBullet.ViewModels.WordlistManagerViewModel.RefreshList() in D:\Projects\Desktop\SilverBullet\OpenBullet\ViewModels\WordlistManagerViewModel.cs:line 102
   to OpenBullet.ViewModels.WordlistManagerViewModel..ctor() in D:\Projects\Desktop\SilverBullet\OpenBullet\ViewModels\WordlistManagerViewModel.cs:line 38
   to OpenBullet.MainWindow..ctor() in D:\Projects\Desktop\SilverBullet\OpenBullet\MainWindow.xaml.cs:line 248
   --- End of internal exception stack trace ---
   to System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   to System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   to System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   to System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   to System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   to System.Windows.Application.DoStartup()
   to System.Windows.Application.<.ctor>b__1_0(Object unused)
   to System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   to System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate
